import {
  FieldType,
  FormLayout,
  ValidationRuleType,
} from "@/features/form-engine/constants/enums";
import type { FormDefinition } from "@/features/form-engine/types";

/** Production Home Loan EMI — input definitions only. */
export const homeLoanEmiProductionForm: FormDefinition = {
  id: "form_home_loan_emi_production",
  name: "Home Loan EMI",
  description:
    "Estimate EMI, interest, total cost, and amortisation for a home loan.",
  calculatorId: "calc_home_loan_emi",
  calculatorSlug: "home-loan-emi",
  layout: FormLayout.TwoColumn,
  submitLabel: "Calculate EMI",
  resetLabel: "Reset",
  showReset: true,
  sections: [
    {
      id: "section_loan",
      title: "Loan details",
      description: "Required inputs for EMI calculation.",
      layout: FormLayout.TwoColumn,
      order: 1,
    },
    {
      id: "section_optional",
      title: "Optional inputs",
      description: "Fees, prepayment, and start date refine the estimate.",
      layout: FormLayout.TwoColumn,
      order: 2,
    },
  ],
  fields: [
    {
      id: "field_loan_amount",
      name: "loanAmount",
      type: FieldType.Currency,
      label: "Loan amount",
      placeholder: "5000000",
      defaultValue: 5000000,
      required: true,
      prefix: "₹",
      unit: "INR",
      helpText: "Sanctioned principal must be greater than 0.",
      tooltip: "Enter the loan principal.",
      sectionId: "section_loan",
      order: 1,
      min: 1,
      max: 100000000,
      validation: [
        {
          type: ValidationRuleType.Required,
          message: "Loan amount is required.",
        },
        {
          type: ValidationRuleType.Min,
          value: 1,
          message: "Loan amount must be greater than 0.",
        },
        {
          type: ValidationRuleType.Max,
          value: 100000000,
          message: "Loan amount cannot exceed ₹10,00,00,000.",
        },
      ],
    },
    {
      id: "field_interest_rate",
      name: "interestRate",
      type: FieldType.Percentage,
      label: "Interest rate (%)",
      placeholder: "8.5",
      defaultValue: 8.5,
      required: true,
      suffix: "%",
      helpText: "Nominal annual rate. Zero is allowed for interest-free loans.",
      sectionId: "section_loan",
      order: 2,
      min: 0,
      max: 30,
      step: 0.05,
      validation: [
        {
          type: ValidationRuleType.Required,
          message: "Interest rate is required.",
        },
        {
          type: ValidationRuleType.Min,
          value: 0,
          message: "Interest rate must be 0 or greater.",
        },
        {
          type: ValidationRuleType.Max,
          value: 30,
          message: "Interest rate cannot exceed 30%.",
        },
      ],
    },
    {
      id: "field_loan_tenure",
      name: "loanTenure",
      type: FieldType.Number,
      label: "Loan tenure",
      placeholder: "20",
      defaultValue: 20,
      required: true,
      helpText: "Enter tenure value; unit is selected separately.",
      sectionId: "section_loan",
      order: 3,
      min: 1,
      max: 480,
      validation: [
        {
          type: ValidationRuleType.Required,
          message: "Loan tenure is required.",
        },
        {
          type: ValidationRuleType.Min,
          value: 1,
          message: "Loan tenure must be greater than 0.",
        },
      ],
    },
    {
      id: "field_tenure_type",
      name: "tenureType",
      type: FieldType.Select,
      label: "Tenure type",
      defaultValue: "years",
      required: true,
      sectionId: "section_loan",
      order: 4,
      options: [
        { value: "months", label: "Months" },
        { value: "years", label: "Years" },
      ],
      validation: [
        {
          type: ValidationRuleType.Required,
          message: "Tenure type is required.",
        },
      ],
    },
    {
      id: "field_processing_fee",
      name: "processingFee",
      type: FieldType.Currency,
      label: "Processing fee (optional)",
      placeholder: "0",
      defaultValue: 0,
      required: false,
      prefix: "₹",
      sectionId: "section_optional",
      order: 5,
      min: 0,
      max: 10000000,
      validation: [
        {
          type: ValidationRuleType.Min,
          value: 0,
          message: "Processing fee cannot be negative.",
        },
      ],
    },
    {
      id: "field_prepayment",
      name: "prepayment",
      type: FieldType.Currency,
      label: "Prepayment (optional)",
      placeholder: "0",
      defaultValue: 0,
      required: false,
      prefix: "₹",
      helpText: "Lump-sum reduction applied to principal before EMI.",
      sectionId: "section_optional",
      order: 6,
      min: 0,
      max: 100000000,
      validation: [
        {
          type: ValidationRuleType.Min,
          value: 0,
          message: "Prepayment cannot be negative.",
        },
      ],
    },
    {
      id: "field_loan_start_date",
      name: "loanStartDate",
      type: FieldType.Date,
      label: "Loan start date (optional)",
      required: false,
      helpText: "Used for schedule labelling / metadata only.",
      sectionId: "section_optional",
      order: 7,
    },
  ],
};
